### ISSUE TITLE
Getting an Error when asking for the Modified By or Created By fields

### ISSUE THREAD

**Issue by BingoLaHaye** [LukasK13/sharepointr#10]
I keep getting this error when I try to extract the created by or modified by fields:

 Status Code 400: Request failed.
<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-1, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="en-US">The query to field 'Editor' is not valid. The $select query string must specify the target fields and the $expand query string must contains Editor.</m:message></m:error>

**Comment by LukasK13** [comment]
Hey @BingoLaHaye 
Sorry to hear that.
I need some code in order to hunt the bug.

**Comment by BingoLaHaye** [comment]
Here is my session info
```
R version 4.0.0 (2020-04-24)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18363)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] magrittr_1.5      sharepointr_1.0.0

loaded via a namespace (and not attached):
 [1] httr_1.4.1             compiler_4.0.0         R6_2.4.1               tools_4.0.0            SPdashboard_0.0.0.9000
 [6] curl_4.3               tinytex_0.23           xml2_1.3.2             stringi_1.4.6          jsonlite_1.6.1        
[11] xfun_0.14 
```

I have this CRM List that I have. And it currently has a couple of normal fields and some auto-generated fields. These are like the "Created"(Date), "Modified" (Date), and "Created By"(Who created that line) and "Modified By" (Who last modified that line). And when I try to add "Created By" and "Modified By", it errors out. These fields show in the sp_con object but I can't seem to query them. 

Here is my code:

```
sp_con <- sp_connection(Address = site, Username = user, Password = pass, Office365 = T)
lists <- sp_getLists(sp_con, raw = F)
#This is the ID for the CRM gotten from the above commented out function
crm_id <- "630febc4-8244-4b71-a247-38adc6c0d512"

blep_list <- sp_list(sp_con,listID = crm_id)  %>%
  sp_select(Title, `Contact Email`, `Contact Phone`, `Organization `, `Tech Area`, `ETC connection`, `Relationship`,
            `Modified`, `Contact Last Name`, `Modified By`,`Created By`, `Created`) %>%
  sp_collect(verbose = T, expand = T)
bloop <- sp_readListData(con = sp_con, listID = crm_id, expand = T)  
```

And here is the output that I get:

```
Error in sp_request(table$con, request) : 
  Status Code 400: Request failed.
<?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-1, Microsoft.SharePoint.SPException</m:code><m:message xml:lang="en-US">
The query to field 'Author' is not valid. The $select query string must specify the target fields and the $expand query string must contains Author.
</m:message></m:error>
```

I'm kinda confused because I have the expand listed as `TRUE` but it keeps giving me this error.

**Comment by LukasK13** [comment]
#8 
The problem here is, that querying look-up columns (like _created by_ or _modified by_ which are person look-ups) is not supported (yet). As I just started my masters thesis, I'm not sure when I will be able to implement this.

**Comment by BingoLaHaye** [comment]
Gotcha. I might see if I can fork it over this weekend and see if I can help in any way. (I'm not the greatest with API's but maybe I can help in some way).

**Comment by LukasK13** [comment]
That sounds great. I think you don't have to deal much with the sharepoint API. If you have a look at [this](R/sharepoint_users.R) file, you will find an algorithm for retrieving user information. I think detecting that a column is a user look up columns in `sp_collect()` and then calling `sp_users` for this column should do it.

**Comment by BingoLaHaye** [comment]
Thanks @LukasK13 for the tip. I haven't had much time to take a look at it yet, but thanks for pointing me in the right direction.

**Comment by influential-eliot** [comment]
I know that this is old, but using the RenderListDataAsStream endpoint _might_ just help if you incorporate it the right way.

https://learn.microsoft.com/en-us/sharepoint/dev/sp-add-ins/working-with-lists-and-list-items-with-rest#retrieve-items-as-a-stream

*EDIT*
Confirmed ... I got this to drop me the 'Editor' details in a response where I specifically called out a view ID which included this data. It also worked without any other parameters (url or body) than this query: `?FilterField1=ID&FilterValue1=5`

But it probably wouldn't hurt to include `&Field=Editor` in the query or the following in the body:
```
{
  "parameters": {
    "ExpandGroups": true
  }
}
```
