### ISSUE TITLE
tiny mistake in description

### ISSUE THREAD

**Issue by dikke-nek** [LukasK13/sharepointr#13]
Thank you for your package,
I noticed a missing "=" in this tuto line  (Pipeline tools for reading) : 
sp_list = sp_list(sp_con, "yourList") %>% sp_filter(yourColumn1 **=** "yourValue") %>% sp_select(yourColumn2) %>% sp_arrange(yourColumn2) %>% sp_collect()

correction:
sp_list = sp_list(sp_con, "yourList") %>% sp_filter(yourColumn1 == "yourValue") %>% sp_select(yourColumn2) %>% sp_arrange(yourColumn2) %>% sp_collect()

**Comment by LukasK13** [comment]
Thank you.
