### ISSUE TITLE
Can't get data for calculated columns of a list

### ISSUE THREAD

**Issue by lucazav** [LukasK13/sharepointr#14]
The `sp_readListData` function can't manage calculated columns. I verified that calculated columns are sow as "hidden" columns. One workaround could be to allow the new `hidden` parameter also for the `sp_readListData` function.

**Comment by LukasK13** [comment]
Thank you @lucazav for the report. Unfortunately, I no longer have access to a SharePoint license and I am no longer using R. Because of that I cannot fix this issue. Pull requests are very welcomed.

**Comment by MatiasIslaA** [comment]
I tried to add this feature in #15. This is my first time modifying a R package, so please use it with caution. There isn't much difference in the code, but it does work with my Sharepoint Lists

**Comment by LukasK13** [comment]
Thank you for your pull request. Is it possible for you to keep my original formatting? Otherwise your changes are not directly visible.

**Comment by MatiasIslaA** [comment]
Done, and the difference is minimal haha. I hope it solves the problem for @lucazav

**Comment by lucazav** [comment]
Thank you @MatiasIslaA , I'll try the new version asap. In the meantime I wrote a function that passed the output of a call to the SharePoint API. Thanks!

**Comment by MatiasIslaA** [comment]
Great @lucazav, let me know if it worked. Could you please share your function with me? I would really appreciate it. Thank you!

**Comment by LukasK13** [comment]
Thank you for your work. I merged your pull request.
