### ISSUE TITLE
Unable to get lists or lists contents

### ISSUE THREAD

**Issue by FireFighter1017** [LukasK13/sharepointr#2]
I was able to connect with this string:
sp_con = sp_connection("https://xxxxxxxxxx.sharepoint.com/sites/our_site/", "username", "password", Office365 = F)

But when I try sp_getLists(sp_con) or sp_List(sp_con, "my_list") it fails with 401: request failed.

**Comment by LukasK13** [comment]
Based on your given hostname layout, I would guess you are trying to access a SharePoint online site. Therefore you have to set Office365 = T while connecting.

So your command for connecting should look like this:
sp_con = sp_connection("https://xxxxxxxxxx.sharepoint.com/sites/our_site/", "username", "password", Office365 = T)

Does this resolve your issue?

**Comment by FireFighter1017** [comment]
That's what I tried first and it rejected the authentication.
Then I tried with Office365=F and it worked but then I couldn't get lists

**Comment by LukasK13** [comment]
Ok so you are trying to connect to ShatePoint online and therefore you have to use Office365 = T. Setting this argument causes the sp_connection method to request an access token from microsoft.
Using Office365=F causes no additional request to be made an therefore no error will be thrown.

Can you provide the full error message and log for Office365=T?

**Comment by FireFighter1017** [comment]
Ok, I dunno why but it seems when I'm outside our company's network the authentication works.
But I still can't get any lists.

Here's the script:
> sp_con = sp_connection("https://ourdomain.sharepoint.com/sites/our_sub_site", "username", "password", Office365 = T)
> feat <- sp_list(sp_con, "Backlog Features")
Error in sp_request(con, request) : Request didn't return valid JSON.
> sp_getLists(sp_con)
Error in sp_request(con, "lists") : Request didn't return valid JSON.
> sp_getLists(sp_con, raw=T)
Error in sp_request(con, "lists") : Request didn't return valid JSON.

**Comment by LukasK13** [comment]
Can you try to run your script again? Make sure you reinstall the sharepointr library before.
Also please make sure you use your email address which you use to sign in at microsoft as username .

**Comment by FireFighter1017** [comment]
I forked your code and tried a couple of things.
- added /web/ at the end of the address
- debugging to see if the response gives any hints
- Copied the address from the response into a browser window to confirm the API works, and it did return an XML response.

I could connect, but all I could ever get is an HTTP error 500 when trying to get the list collection (/_api/web/lists, or /_api/lists)
And I tried with a site on which I am owner.

Looks like Sharepoint now defend itself from bots.
That I might have to get a OAuth token in order to do anything.

**Comment by LukasK13** [comment]
I don't think Sharepoint is defending itself from bots, as this REST-API is an official way of consuming Sharepoint data. I tested all methods with our Sharepoint tier and everything seems to work perfect.
Can you try to execute the following
```
sp_con = sp_connection("https://xxxxxxxxxx.sharepoint.com/sites/our_site/", "username", "password", Office365 = T)
print(sp_con$cookie)
```
and see, if there's any value for `rtFa=` and `FedAuth=`?
This way we can determine if the problem occurs during the token request or during the list request.

**Comment by FireFighter1017** [comment]
> sp_con$Cookie
[1] "rtFa=; FedAuth="

It looks empty

**Comment by LukasK13** [comment]
This means even the authentication fails. Can you try using only `https://xxxxxxxxxx.sharepoint.com` as address. Please don't forget to use your e-mail address as username and see if this works and you are receiving the cookies.
Otherwise try to follow the instructions on this [website](https://paulryan.com.au/2014/spo-remote-authentication-rest/) to check if receiving an access token manually works.

**Comment by FireFighter1017** [comment]
Using only domain name as sp_con$Address results in this:
`Receiving access cookies failed`

**Comment by LukasK13** [comment]
Please follow the instructions on [this](https://paulryan.com.au/2014/spo-remote-authentication-rest/) page, to see where your problem is, as it works perfectly for our company.

**Comment by kelnerrr** [comment]
I too have a similar problem. I can't get it working.
I can get the list through API at:
https://mycompany.sharepoint.com/sites/RDv3/saasops/_api/lists(guid'xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx')/Items

My `sp_con` seems to look ok. It has a cookie, my e-mail address as a login, Office365 set to true. The command I used is:
`sp_con = sp_connection("https://mycompany.sharepoint.com/sites/RDv3/saasops/", "e-mail", "pass", Office365 = T)`
With `sp_getLists(sp_con)` I get:

> Error in sp_request(con, "lists") : Status Code 403: Request failed.
> <?xml version="1.0" encoding="utf-8"?><m:error xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"><m:code>-2147024891, System.UnauthorizedAccessException</m:code><m:message xml:lang="en-US">Access denied. You do not have permission to perform this action or access this resource.</m:message></m:error>

**Comment by LukasK13** [comment]
Thanks four your report @kelnerrr
Is `sp_con$Address` identical to https://mycompany.sharepoint.com/sites/RDv3/saasops/_api ?
I would guess this is related to your request URL, as you are trying to access a subpage. Can you try accessing your webroot: https://mycompany.sharepoint.com and see if this works?
As I am not allowed to create subsites, I cannot debug this usecase.

**Comment by kelnerrr** [comment]
Sorry for the very late response.
Yes, `sp_con$Address = https://mycompany.sharepoint.com/sites/RDv3/saasops/_api/` (with the slash at the end).
I tried removing subfolders but I always get 403 or 404 error message.
I get 403 for `https://mycompany.sharepoint.com/_api/`.

**Comment by LukasK13** [comment]
You must not include `api_` in your URL.

**Comment by kelnerrr** [comment]
As I mentioned in a previous post I execute:
`sp_con = sp_connection("https://mycompany.sharepoint.com/sites/RDv3/saasops/", "e-mail", "pass", Office365 = T)`.
With `sp_getLists(sp_con)` I get error 403.
The `_api/` is added by `sp_connection()` function.

**Comment by kelnerrr** [comment]
I made it work! Just by mistake, I used `c()` and not `paste0()` as I meant to and the below code worked.

```
sp_con = sp_connection("https://mycompany.sharepoint.com/sites/RDv3/saasops/", "email", "pass", Office365 = T)
FedAuth = str_extract(sp_con$Cookie, 'Fed.*')
rtFa = str_extract(sp_con$Cookie, '.*(?=;)')
sp_con$Cookie = c(rtFa, FedAuth)
sp_getLists(sp_con)
```

I wanted to change the order of `FedAuth` and `rtFa` to test if it helps. I suppose it now might have created two cookies instead of one. When I visit SP 365 in the browser I see two cookies.
