### ISSUE TITLE
No cookies

### ISSUE THREAD

**Issue by Ranae** [LukasK13/sharepointr#3]
I just started at a company that uses sharepoint and as an R user, I was really happy to find this package! I think I am having trouble getting authenticated. I don't get an error, but if I try `print(sp_con$cookie)`, I get "NULL". 

Is it possible my company just isn't set up to do this?

**Comment by LukasK13** [comment]
Hi @Ranae 
What kind of sharepoint are you trying to connect to, SharePoint server or SharePoint 365? In case you are trying to connect to SharePoint Server, there is no cookie generated.

**Comment by kelnerrr** [comment]
@Ranae, there is a capital C in Cookie. Check: `print(sp_con$Cookie)`.

**Comment by LukasK13** [comment]
I'm going to close this issue due to inactivity. @Ranae feel free to reopen if the bug still exists.
