### ISSUE TITLE
Fail when different number of columns between pages

### ISSUE THREAD

**Issue by kelnerrr** [LukasK13/sharepointr#4]
While running `sp_readListData()` function I got the error:
```
Error in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match
```

I debugged it and it is caused by the difference in number of columns between pages of results.
I replaced `data = rbind(data, data_temp)` with `data = bind_rows(data, data_temp)` (needs `dplyr` package) and it works correctly.

**Comment by LukasK13** [comment]
Hi @kelnerrr,
Thank you very much for your report and the bugfix. However I can not fully understand why the number of columns would differ for two result pages, as they are both parts of the same list.
Did you have a look which columns differed, i.e. if only internal columns differed or also user defined (your columns)?
Are you using `expand = TRUE`?

**Comment by kelnerrr** [comment]
The column is user defined ('Customer number', internal name = 'Customer_x0020_number').
I checked that on the first page (100 results) all the values are NAs and type of is 'logical'.
On the second page, there are some values and the type is 'character'.

Also, some other columns are of type different than 'character' and are cut out. Most of them are of logical type (they are empty), one is a list.

This fails because of this check of a type:
```
cols = names(if (con$Office365) response$content$value else response$content$d$results)[which(unname(unlist(lapply(if (con$Office365) response$content$value else response$content$d$results, typeof))) == "character")]
```

No, I am not using `expand = TRUE`.
