### ISSUE TITLE
Error in sp_readListData

### ISSUE THREAD

**Issue by saber552** [LukasK13/sharepointr#8]
sp_readListData returns

Error in `[.data.frame`(data_temp, , columnNamesInternal) : 
  undefined columns selected

**Comment by LukasK13** [comment]
I need some more information on your code and a reproducible example in order to look into this.

**Comment by saber552** [comment]
sp_con = sp_connection("https://[company]/sites/[site]", ":", ":", Office365 = T)
sp_getListColumns(sp_con, listName = "[listname]") # this works
data <- sp_readListData(sp_con, listName = "[listname]", expand = F) # Doesn't work, tried T and F

**Comment by LukasK13** [comment]
Thank you for the code example.
However I still need some data including original column names and data types (values can be redacted) to dig into this as this problem is probably related to your dataset.

**Comment by saber552** [comment]
Here are the types:

![image](https://user-images.githubusercontent.com/63260803/78603681-8b564a80-7826-11ea-8752-b7a33f045ebe.png)

I can't really give the column names but per the column name pull they have had their spaces replaced with "%20", and if special characters might be a problem several have : , or + in them.

**Comment by saber552** [comment]
If sp_readListData could be modified so I can specify column names to pull I could at least find the offending column.

**Comment by LukasK13** [comment]
Sorry for the late response. So the problem seems to be to column of type `Person or Group`.
Using the dplyr-style methods for reading from lists you are able to select specific columns in your query.
As querying columns of type `Person or Group` only returns the persons UID, I need so time to figure out how to request the persons name.

**Comment by saber552** [comment]
Can you provide an example of how to pull one column with dplyr-style methods?

**Comment by LukasK13** [comment]
You can find an example in the [Pipeline Tools-Section of the ReadMe](https://github.com/LukasK13/sharepointr#pipeline-tools-for-reading).

**Comment by oestergaardn** [comment]
Hi,
First of all, great packages! I have the same problem, I cannot use sp_readListData for lists with People lookups. I have tried to work around these columns by using sp_select but I cannot make it work on readlistdata.

data = sp_readListData(sp_con, "MY LIST") %>% sp_select(Column1, `Column2 with space`)

I can see the list and access. I'm using Office365.

Any help would be appreciated.

**Comment by LukasK13** [comment]
Hi @oestergaardn 
Thank you very much.
The lookup of people is giving me a hard time, so unfortunately I have no solution so far.
For your problem with `sp_select`:
Can you provide any error message?

**Comment by oestergaardn** [comment]
Thank you for a fast reply. I don't need the columns so I basically just need to exclude them and that's why I assume sp_select is the right way to go?

**> data = sp_readListData(sp_con, "MyListName") %>% sp_select(Column1, Column2)**
_Error in sp_select(., Column1, Column2) : 
  Invalid SharePoint list._

In the documentation for sp_collect, it says "Title" is this just an example of a column name or do I need to specify the list again after the pipes?

**Comment by LukasK13** [comment]
Yes, this is the right way to go if you want to retrieve only some specific columns.
However I overlooked a mistake in your code: according to the [readme](https://github.com/LukasK13/sharepointr#pipeline-tools-for-reading) you need to use the function `sp_list()` to specify your list in the pipeline, so your code will look as follows:
```
sp_con = sp_connection("https://you.sharepoint.com/", "YourUsername", "YourPassword", Office365 = T)
sp_list = sp_list(sp_con, "MyListName") %>% sp_select(Column1, Column2) %>% sp_collect()
```
The pipeline is a mix up of dplyr style syntax and the connection handling of DBI.

**Comment by oestergaardn** [comment]
Thank you so much LukasK13!
It works. I couldn't get the sp_collect() to work earlier - thanks
Looking forward to see if you manage to find a fix for lookup columns!

**Comment by oestergaardn** [comment]
@LukasK13: I just tested and it seems like the problem occur for all lookup columns - and not specifically for person lookup.

**Comment by LukasK13** [comment]
You are absolutely right.
