### ISSUE TITLE
Receiving access cookies failed.

### ISSUE THREAD

**Issue by Andrew-Billington** [LukasK13/sharepointr#9]
When I try to create a connection using the code below (domain, email and password removed), I get the error Receiving access cookies failed.
 
sp_con = sp_connection("https://XXX.sharepoint.com",
                                    "EMAIL",
                                    "PWD",
                                    Office365 = T)

Any suggestions on how to fix this?

**Comment by LukasK13** [comment]
You could try going through the function `sp_connection()` defined [here](R/sharepoint_driver.R) by hand to find the error as the debug output of this function is very limited.
